version = 0.1

[default.deploy.parameters]
stack_name = "my-first-serverless"
resolve_s3 = true
s3_prefix = "my-first-serverless"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
confirm_changeset = true

[default.global.parameters]
region = "eu-central-1"
